apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: apache-deployment
  labels: 
    app: apache
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector: 
    matchLabels: 
      app: apache
  template: 
    metadata: 
      labels: 
        app: apache
    spec: 
      containers:
      - name: apache-container
        image: httpd:latest
        ports:
        - name: apache-port
          containerPort: 80

        resources:
          requests: 
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
            
        